---
version: 2
updates:
  - package-ecosystem: "pip"
    insecure-external-code-execution: allow
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/Kiev"
    open-pull-requests-limit: 1
    reviewers:
      - "dmytrostriletskyi"
