---
name: Trunk workflow

on:
  push:
    branches:
      - master

jobs:
  make-release:
    runs-on: [ubuntu-latest]
    outputs:
      project_version: ${{ steps.get_project_version.outputs.project_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install operating system requirements
        run: apt-get update && apt-get install -y build-essential libgomp1
      - name: Get a project version
        id: get_project_version
        run: echo "::set-output name=project_version::$(make get-project-version)"
      - name: Install project requirements
        run: pip3 install -r requirements/ops.txt
      - name: Make a release
        env:
          NEXUS_GH_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
        run: |
          python3 ops/make_release.py master ${{ steps.get_project_version.outputs.project_version }}
