---
name: Trunk workflow

on:
  push:
    branches:
      - master

jobs:
  make-release:
    runs-on: [ubuntu-latest]
    outputs:
      project_version: ${{ steps.get_project_version.outputs.project_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Get a project version
        id: get_project_version
        run: echo "::set-output name=project_version::$(make get-project-version)"
      - name: Install project requirements
        run: make install-requirements
      - name: Make a release
        env:
          ACCESS_TOKEN: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}
        run: |
          project-version release \
              --provider=GitHub \
              --organization=dmytrostriletskyi \
              --repository=project-version \
              --branch=master \
              --project-version=${{ steps.get_project_version.outputs.project_version }}
